### ISSUE TITLE
Add support for arbitrary number of search providers.

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/code-bing#2]
Issue for #1.

**Comment by SrTobi** [comment]
Calling in @jacobhands as author.

**Comment by SrTobi** [comment]
Closed #1. There are still some things to consider:
1. Currently the old `searchprovider` overwrites the new `defaultProvider`. Thats not what we want.
2. One can not add something to `codebing.searchProviders`. One can only overwrite it. Maybe we should move the default search providers into the code and merge/overwrite them with `codebing.searchProviders`. What do you say @jacobhands.
3. The readme must be updated.

**Comment by jahands** [comment]
1. This is for backwards compatibility with v0.0.1's old `searchprovider` option.
2. This is a feature so that users have control over the default providers. More detail on #3

**Comment by SrTobi** [comment]
ok, I fixed some typos and merged #5. I also registered an event listener so the configuration is checked every time it is changed (See d1b028eb311743b6a06d45eebd06f7dc2368be80).

readme is still missing though :)

**Comment by SrTobi** [comment]
I think this is done. for new things open a new issue.

**Comment by jahands** [comment]
Will do! After the mess I made of git, I'm going to try to keep commits low and rebase to SrTobi/code-bing master branch before pushing to my branch. Should make merging easier.
