### ISSUE TITLE
Create vnext branch so people can easily clone the repo and get the latest stable version

### ISSUE THREAD

**Issue by jahands** [SrTobi/code-bing#23]
Sometimes people may want to manually install via `git clone.` So that they don't get a possibly messed up version, we should use `vnext` branch for dev, and then publish stable versions to master.

**Comment by jahands** [comment]
Went ahead and created a [vnext branch](https://github.com/SrTobi/code-bing/tree/vnext) branch (I'm impatient) but won't do anything with it till you're onboard with it.

**Comment by SrTobi** [comment]
hmmm, yeah good idea. My intuition would have been to leave master as the main development branch and create a stable branch (so the other way around). I will consult some best practices.

**Comment by jahands** [comment]
Maybe I'm just used to Go...where by default, importing libraries uses latest commit on master.

I've seen it done both ways, but as a distribution point, I think it's nice being able to just clone master and get a working version.

**Comment by SrTobi** [comment]
ok yeah, but I want the development branch to be named `develop` ^^

**Comment by SrTobi** [comment]
ok... no let me think about that again^^

**Comment by jahands** [comment]
I like `dev` better than `develop`, I just liked `vnext` because it's version-next. Though it's functionally equivalent to `dev`

**Comment by jahands** [comment]
[from gitter]
One thing to think about, when you go to https://marketplace.visualstudio.com/items/SirTobi.code-bing, there is a link called "Get Started" which links to the repository
So users can go look at it
Then, we happen to be editing the readme for a future update
User sees future documentation for unreleased feature
User tries to use that feature
Feature doesn't work because it's unreleased
Suddenly we've created a poor user experience
That's a bad thing ^^

**Comment by jahands** [comment]
Github projects are the project page that people may see. The default view should reflect the current release imo.

**Comment by SrTobi** [comment]
ok let's create a `dev` branch
