### ISSUE TITLE
Quotation symbol ( " & ' ) should be consistent across the project.

### ISSUE THREAD

**Issue by jahands** [SrTobi/code-bing#30]
This is a style choice that doesn't affect functionality. But consistency would be good. I think maybe the single quote (`'`) may be a good choice as it seems pretty common. Thoughts?

**Comment by SrTobi** [comment]
yeah good idea. It would also be nice to setup some kind of style check that rejects all git commit if the code is malformed.

**Comment by jahands** [comment]
Oh yeah that'd be awesome. I'll submit a PR soon about the quotation thing.

**Comment by SrTobi** [comment]
ok sorry. I have not read your comment correctly: Yes I am for a consistent use of `'` and `"` but I prefer `"`. I only used `'` in the import statements... it's a good question why I did that... :). I also looked for advantages when using `'` but I think http://stackoverflow.com/a/242833/1393971 is a pretty good rule. What do you think?

**Comment by jahands** [comment]
I don't care which we use, I just want it consistent. The SO answer is a good rule.
So: Use `'` only when the string contains `"`, otherwise use `"` to quote all strings. That work?

**Comment by jahands** [comment]
I updated #34 to use double quotes :)

**Comment by SrTobi** [comment]
:+1:
