### ISSUE TITLE
Stackoverflow as default provider

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/code-bing#38]
What happend in #35, #36?

**Comment by jahands** [comment]
#35 was submitted to the wrong branch (master), #36 is because I hit merge before checking the branch.

**Comment by SrTobi** [comment]
ahhh ok... I think that will continue to happen in the feature. Maybe we should change dev -> master, master -> stable. Then this problem is fixed

**Comment by SrTobi** [comment]
Didn't we had this discussion^^

**Comment by SrTobi** [comment]
we can also set dev as the default branch, but thats a little bit weird.

**Comment by jahands** [comment]
Yes, we don't want that because then people visiting the repo will first
see the Readme with information that may have changed since the latest
release on the marketplace.

**Comment by jahands** [comment]
Didn't know about default branch. I guess we could make a stable branch and
set as default, and use master as dev?

**Comment by SrTobi** [comment]
nja... but the default branch is also the base branch for pr's.

**Comment by jahands** [comment]
But then of course people would just submit pr's to stable...
You know what? It's fine....people need to just read CONTRIBUTING.md

**Comment by jahands** [comment]
Let's just keep the dev/master setup.

**Comment by SrTobi** [comment]
I have an idea: we make the master/stable setup but in package.json we change the link to repo/stable

**Comment by jahands** [comment]
I still think dev/master is better. The default view for the repo should be the released/stable version of the extension.

**Comment by jahands** [comment]
When I [google](https://www.google.com/search?q=code-bing&oq=code-bing&aqs=chrome..69i57j69i60l3.2871j0j1&sourceid=chrome&es_sm=93&ie=UTF-8#q=code-bing+vscode+github) for it, it's going to lead me to the master branch.

**Comment by SrTobi** [comment]
ok, I have the exact opposite opinion: if I go to a github page (so... I don't have to, because there is this nice marketplace view) I expect to be on the cutting edge development. And people who use vscode will know how to handle this, especially if they install the extension a manual way.

So, because I am the owner (^^) and because I hate it if I have to change the branch on github to see latest commits, I **decide** that we change to the master/stable system. For all people coming from google or elsewhere we should reference the marketplace site in the readme.

**Comment by jahands** [comment]
Hey no need to get angry :/
That's fine.

**Comment by SrTobi** [comment]
sorry, I didn't want to seem angry (and I am not). I just wanted to do close that fast because I have a train to catch.

I am very happy to not do this alone and I really appreciate your help. Thank you for that. I am looking forward to do nice coding with you in the future (is this an English sentence? hmmm I have the feeling that it sounds a little bit cheesy :smile:)

**Comment by jahands** [comment]
Okay cool! You're English is good, I've had no problem understanding you :)
I'm happy to help with this, it's nice to code with someone else for a
change :)
