### ISSUE TITLE
Default Search Providers are completely overwritten by `codebing.searchProviders`

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/code-bing#4]
One can not add something to codebing.searchProviders. One can only overwrite it. Maybe we should move the default search providers into the code and merge them with codebing.searchProviders. What do you say @jacobhands.

**Comment by jahands** [comment]
I thought about that and decided that it overwriting them is fine. If you want the ones included by default, simply copy them to your user settings.

If you hard code them then the user can't change the shortcut to the default providers.
I wanted people to be able to change `g` to `goog` or `google` if they wanted to.

By letting a user overwrite `codebing.searchProviders`, it allows users to customize all of the default providers or remove the ones they don't want. I consider this a feature.

**Comment by SrTobi** [comment]
:+1: , I think thats fine. Especially because if you add `"codebing.searchProviders"` to your config all searchproviders are automatically preset.
