### ISSUE TITLE
Error Box if the searchprovider is not an url.

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/code-bing#6]
If a searchprovider is set that is not an url, an error box occurs.

```
    "codebing.defaultProvider": "g"
```

![unbenannt](https://cloud.githubusercontent.com/assets/4148534/11460959/d52f4666-96f8-11e5-9c7c-ee83852e47fe.PNG)
- `gggg` is not accepted.
- `g.g` is accepted.
- `http:` is accepted.
- `https:` is accepted.

So we must check if the search string contains an `http(s):` or a `.`.

**Comment by jahands** [comment]
I added the ability for it to resolve keys from `searchProviders` in `defaultProvider` via #5

Also added a method stub to validate the config.

**Comment by jahands** [comment]
Fixed in #5
